---
development:
  cloud_name: ddzdneuxe
  api_key: '555971697581325'
  api_secret: 6PjnLcArSUuziXJyz65DyDnWzls
  enhance_image_tag: false
  static_image_support: false
production:
  cloud_name: ddzdneuxe
  api_key: '555971697581325'
  api_secret: 6PjnLcArSUuziXJyz65DyDnWzls
  enhance_image_tag: false
  static_image_support: true
test:
  cloud_name: ddzdneuxe
  api_key: '555971697581325'
  api_secret: 6PjnLcArSUuziXJyz65DyDnWzls
  enhance_image_tag: false
  static_image_support: false
