# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ddb17700392c99d5d039d3c7b0164e87dcc3f9e0e1531d22fc65ccef139e7a1fd0d24a52e0c10009efc5ab43f801cef59742875edd1fee4c6a8287d405b3a1f

test:
  secret_key_base: 923a49b18afb153672873e09d459abad82252f40d3f1edf0d31f4ee1cc0dbd591d0799481a5245814706e53ae5e1bb325d878d5c3d9fd2b6dd04cea1a905d816

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
