#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AutospotsApp.Resource", IsApplication=true)]

namespace AutospotsApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int StatsDayArray = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AutospotsIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AutospotsIcon24x24 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Iconhdpi = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Iconmdpi = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Iconxhdpi = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Iconxxhdpi = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int smallmenu2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int streets1 = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int LotPickSpinner = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int MainMenuButton = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int MainTitleTextView = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int ParkMeButton = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int ParkMeTitleTextView = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int ParkingStatusTextView = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int SubTitleTextView = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int TitleTextView = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main2 = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int ApplicationName = 2130968579;
			
			// aapt resource value: 0x7f040013
			public const int CantLocateText = 2130968595;
			
			// aapt resource value: 0x7f040015
			public const int ForeNotificationText = 2130968597;
			
			// aapt resource value: 0x7f040007
			public const int InLotButtonText = 2130968583;
			
			// aapt resource value: 0x7f040012
			public const int LetsGoText = 2130968594;
			
			// aapt resource value: 0x7f040014
			public const int LocationDisabledToastText = 2130968596;
			
			// aapt resource value: 0x7f040000
			public const int MainTitleText = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int MenuText = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int NearBuildingButtonText = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int NearestSpotButtonText = 2130968581;
			
			// aapt resource value: 0x7f04000f
			public const int NoLocationToastText = 2130968591;
			
			// aapt resource value: 0x7f040002
			public const int ParkMeButtonText = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int PlanTripButtonText = 2130968584;
			
			// aapt resource value: 0x7f04000d
			public const int PlanTripMenuText = 2130968589;
			
			// aapt resource value: 0x7f04000b
			public const int PreferencesButtonText = 2130968587;
			
			// aapt resource value: 0x7f040016
			public const int SelectABuildingText = 2130968598;
			
			// aapt resource value: 0x7f040018
			public const int SelectAParkingLotText = 2130968600;
			
			// aapt resource value: 0x7f04000e
			public const int StatSpinnerPrompt = 2130968590;
			
			// aapt resource value: 0x7f040009
			public const int StatisticsButtonText = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int StatisticsMenuText = 2130968588;
			
			// aapt resource value: 0x7f040001
			public const int SubTitleText = 2130968577;
			
			// aapt resource value: 0x7f04000a
			public const int ViewLotsButtonText = 2130968586;
			
			// aapt resource value: 0x7f040010
			public const int WaitingForLocationText = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int WaitingForSpotText = 2130968593;
			
			// aapt resource value: 0x7f040017
			public const int or = 2130968599;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
